#!/bin/bash

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

STATUS_FILE="/var/lib/dpkg/status"
BACKUP_FILE="${STATUS_FILE}.bak"

backup() {
# Verifica se já existe um backup. Se não existir, cria o primeiro.
if [ ! -f "$BACKUP_FILE" ]; then
    echo -e "${BLUE}[+] Criando backup inicial do banco de dados dpkg...${NC}"
    cp "$STATUS_FILE" "$BACKUP_FILE"
else
    echo -e "${YELLOW}[!] Backup anterior detectado. Criando cópia de segurança da sessão...${NC}"
    cp "$STATUS_FILE" "${STATUS_FILE}.tmp_bak"
fi
}
_system() {
echo -e "${BLUE}[*] Neutralizando systemd e configurando machine-id...${NC}"
dbus-uuidgen > /etc/machine-id 2>/dev/null
ln -sf /bin/true /usr/bin/systemctl
}
trigger() {
    echo -e "${BLUE}[*] Forçando atualização para identificar pacotes quebrados...${NC}"
    
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y > /dev/null 2>&1
    apt-get upgrade -y -o Dpkg::Options::="--force-confold" > /dev/null 2>&1
    pid=$!
    frames="/ | \ -"
    while kill -0 $pid 2>/dev/null; do
        for frame in $frames; do
            echo -ne "\r${YELLOW}[$frame] Diagnosticando sistema... aguarde.${NC}"
            sleep 0.2
        done
    done
    echo -e "\n${GREEN}[+] Diagnóstico concluído.${NC}"
}
confi() {
# Pega a lista de pacotes travados
broken_pkgs=($(dpkg -l | grep -E '^[a-z][U|F|t|H]' | awk '{print $2}'))

if [ ${#broken_pkgs[@]} -eq 0 ]; then
        echo -e "${YELLOW}[+] Nenhum pacote quebrado encontrado..${NC}"
        return
    fi
echo -e "${BLUE}[*] Ajustando banco de dados dpkg...${NC}"
for pkg in "${broken_pkgs[@]}"; do
    FILE="/var/lib/dpkg/info/$pkg.postinst"
    if [ -f "$FILE" ]; then
        echo -e "${RED}[!] Neutralizando: $FILE${NC}"
        echo -e "#!/bin/sh\nexit 0" > "$FILE"
        chmod +x "$FILE"
    fi 

    echo -e "${GREEN}[+] Aplicando patch via AWK: $pkg${NC}"
    awk -v p="$pkg" '
    BEGIN { target="Package: " p }
    $0 ~ "^" target "(:| )" || $0 == target { f=1 }
    f && /^Status:/ { print "Status: install ok installed"; next }
    f && /^Config-Version:/ { next }
    f && /^$/ { f=0 }
    { print }' "$STATUS_FILE" > "${STATUS_FILE}.tmp" && mv "${STATUS_FILE}.tmp" "$STATUS_FILE"
   done
}
limpeza() {
#  Configuração e Limpeza
echo -e "${BLUE}[*] Destravando o dpkg e limpando cache...${NC}"
export DEBIAN_FRONTEND=noninteractive
dpkg --configure -a --force-confnew

apt-get clean
apt-get update

echo -e "${GREEN}[√] Pronto! Sistema destravado e atualizado.${NC}"
}
backup
_system
trigger
confi
limpeza
